### ISSUE TITLE
Feature request: height-triggered roof tiles

### ISSUE THREAD

**Issue by baileywick** [League-of-Foundry-Developers/roofs#2]
Depending on the altitude/height of a player token, a Roof tile will appear or disappear. 

Given a 2 story house scenario: A player at height 0 would cause all roofs above him to disappear. At level 10, only one roof would disappear. At level 20, no roofs disappear and that player would effectively be standing on the roof. A Roof tiles could have a set height as a variable. Any Token meeting or exceeding that height would not trigger the roof to disappear.

Combined with Wall Height module and Multilevel Token module, this could open the door to creating Multilevel buildings in scenes. MLT has the ability to trigger a macro, in this case a macro that changes a player's altitude. This would allow for players to traverse stairs and then automatically render the new level complete with reconfigured walls.

Combining all of this with Token Attacher would create the ability to deploy entire maps like ships, buildings and magic towers on any map.

**Comment by akrigline** [comment]
I think this is a bit beyond the scope of Roofs, and since "Overhead tiles" is slated for 0.8.x core foundry, I hope some of its changes would make such a module easier or even unnecessary.

That said, I have some questions for your use cases:
- What is shown in the case where two different tokens are at different elevations? I.e. 1 at "second floor" and one at "third floor"?
- What does the GM see in all this?

**Comment by baileywick** [comment]
What is shown in the case where two different tokens are at different
elevations? I.e. 1 at "second floor" and one at "third floor"?

Each Token would see their respective walls and floor configuration and any
other Tokens at their level.

What does the GM see in all this?

The GM could see all Tokens. And maybe clicking a Token renders that
Token's level configuration view (walls and floor) for the GM.

**Comment by akrigline** [comment]
> Each Token would see their respective walls and floor configuration and any other Tokens at their level.

This is the tricky part right? Foundry's "Vision" isn't really based on tokens, it's based on players. A player can have vision from multiple tokens (either the whole party sharing vision or say a Familiar). You could base it on only the selected token, but that gets clunky because if you deselect that token, but select another token which cannot see the first token, you're toast. That's why foundry shows all the possible vision for a player when there are no tokens selected, which brings us back to the start 😵 .

I think these are all solvable problems, but the manner in which we solve them quickly blows the scope up.

**Comment by Moerill** [comment]
another big problem woudl be for walls to know smth like "elevation".. which is.. kind of worth its own module (the whole vision got elevation idea would be quite some work)
so i'm with @akrigline here that its kind of out of scope of this module and stuff like having a second scene or a teleport or so to the next lvl would be more feasible and usable.

**Comment by baileywick** [comment]
The Wall Height module already works great for this. You can set a wall to
go from say, 8 feet to 16 feet. When a token is set to elevation 8ft,
through MLT's macro for example, the walls are all "in effect" for that
token. But a token at level 0 would see an entirely different wall
configuration. I've tested this and it works great. But the above floors
just need to disappear to make it complete.

**Comment by anthonyronda** [comment]
@baileywick we're considering archiving this repo, so if you have any final thoughts on any of the open issues, get them in soon! I haven't read up on all of your Issues but theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about more ideas over there or on the League Discord

Edit: all the existing releases will still be accessible! Wanted to make sure you knew that 😅

**Comment by baileywick** [comment]
Archive away! Better Roofs has been everything I've been hoping for and
more. Great module to carry the torch.
