### ISSUE TITLE
Bug, it shows roofs everywhere

### ISSUE THREAD

**Issue by NukeMaster0** [League-of-Foundry-Developers/roofs#3]
Video says everything, I have also tested this module by itself in a new world and I get the same issue.

https://user-images.githubusercontent.com/68701755/104113180-0cb2a000-52c5-11eb-951a-c257cd009abb.mp4

**Comment by Moerill** [comment]
Heya, thank for the bug report.  
This issue is supposed to be fixed with the newest update 0.1.4.  
Please report back whether you're on that version or not.  

If you're not, you probably have to reinstall the module, since you're on the old branch.   
Old branch? what do i mean?  
This module got adopted by the League of extraordinary FoundryVTT developers, since Vance, the original author, is currently not available. Currently the process of adoption needs the user to reinstall that module.

**Comment by NukeMaster0** [comment]
Yes! It worked, thank you!
All I did was uninstall and reinstalled.
